### PR TITLE
Add 17

### PR DESCRIPTION
**Pull request by daveisfera**
https://www.postgresql.org/about/news/postgresql-17-released-2936/

NOTE: this is using the `rc1` image since the images for the official release aren't available yet

### CODE REVIEW

**Comment by tianon** [comment]
Thank you!  My automation picked up 17 in https://github.com/tianon/docker-postgres-upgrade/commit/ecf607ff902c236affdd789bf359a5ebd1d52922, and I'd prefer not to `ENV foo=bar` here (https://github.com/moby/buildkit/issues/5130). :+1:

**Comment by daveisfera** [comment]
Thanks for getting that out!

Good luck on the `ENV` thing, but considering they [dropped the `version` tag with the basic argument of "we don't want to use it"](https://github.com/compose-spec/compose-spec/blob/main/spec.md#version-and-name-top-level-elements), I wouldn't hold your breath on getting that stance changed

**Comment by tianon** [comment]
The compose team and the build team are separate folks (both coworkers of mine but that clearly doesn't give me any extra sway 😂)

**Comment by tianon** [comment]
Fwiw, I do agree they shouldn't have removed that though!

**Pull request closed without merging**
